### ISSUE TITLE
No support for .Net framework 4.7.2?

### ISSUE THREAD

**Issue by Prikalel** [lucasluizss/Tyrion.CQRS#5]
![Мегамозг](https://github.com/lucasluizss/Tyrion.CQRS/assets/67920266/d184c456-4093-4717-8bd4-86ae8f1e9aad)

**Comment by asyncLucas** [comment]
Currently, this library is implemented using dotnet 3.1. I hope I can get it running on dotnet standard in the future. Contributions are welcome.

**Comment by asyncLucas** [comment]
v1.1.5 launched with dotnet standard compatibility
